spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    url: jdbc:h2:mem:mygraduation
    username: sa
    password:

  cache:
    type: caffeine
    cache-names: restaurant_with_menu, menus_by_restaurant, vote_results, today_winner
    caffeine:
      spec: maximumSize=100, expireAfterWrite=1h

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    root: WARN
    ru.alexeev.mygraduation: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

springdoc.swagger-ui.path: /
